#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-kotlinx-coroutines
Version  : 1.1.0
Release  : 1
URL      : https://github.com/Kotlin/kotlinx.coroutines/archive/1.1.0.tar.gz
Source0  : https://github.com/Kotlin/kotlinx.coroutines/archive/1.1.0.tar.gz
Source1  : https://repo.gradle.org/gradle/libs-releases/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.1.1/kotlinx-coroutines-core-1.1.1.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.1.1/kotlinx-coroutines-core-1.1.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: mvn-kotlinx-coroutines-data = %{version}-%{release}
Requires: mvn-kotlinx-coroutines-license = %{version}-%{release}
BuildRequires : buildreq-mvn
BuildRequires : buildreq-qmake
BuildRequires : gradle

%description
# kotlinx.coroutines
[![official JetBrains project](http://jb.gg/badges/official.svg)](https://confluence.jetbrains.com/display/ALL/JetBrains+on+GitHub)
[![GitHub license](https://img.shields.io/badge/license-Apache%20License%202.0-blue.svg?style=flat)](http://www.apache.org/licenses/LICENSE-2.0)
[![Download](https://api.bintray.com/packages/kotlin/kotlinx/kotlinx.coroutines/images/download.svg?version=1.1.0) ](https://bintray.com/kotlin/kotlinx/kotlinx.coroutines/1.1.0)

%package data
Summary: data components for the mvn-kotlinx-coroutines package.
Group: Data

%description data
data components for the mvn-kotlinx-coroutines package.


%package license
Summary: license components for the mvn-kotlinx-coroutines package.
Group: Default

%description license
license components for the mvn-kotlinx-coroutines package.


%prep
%setup -q -n kotlinx.coroutines-1.1.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-kotlinx-coroutines
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-kotlinx-coroutines/LICENSE.txt
cp license/third_party/minima_LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-kotlinx-coroutines/license_third_party_minima_LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.1.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.1.1/kotlinx-coroutines-core-1.1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.1.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.1.1/kotlinx-coroutines-core-1.1.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.1.1/kotlinx-coroutines-core-1.1.1.jar
/usr/share/java/.m2/repository/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.1.1/kotlinx-coroutines-core-1.1.1.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-kotlinx-coroutines/LICENSE.txt
/usr/share/package-licenses/mvn-kotlinx-coroutines/license_third_party_minima_LICENSE.txt
